### ISSUE TITLE
CI: coverage report broken

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#360]
Currently, somehow the test coverage report is broken.

Failed to send the report from Travis CI to Coveralls:
https://travis-ci.org/github/vermaseren/form/jobs/708419561#L1875

```
Traceback (most recent call last):
  File "/home/travis/.local/bin/coveralls", line 11, in <module>
    sys.exit(run())
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/__init__.py", line 106, in run
    return report.post_report(cov_report, args)
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/report.py", line 13, in post_report
    verify=(not args.skip_ssl_verify))
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

As a result, the coverage has not  been updated:
https://coveralls.io/github/vermaseren/form?branch=master

**Comment by tueda** [comment]
It seems that if we upgrade the distribution on Travis CI from `trusty` to `xenial` or `bionic` then the SSH handshake succeeds. But this change introduces other failures for `parform`, `form-i386` and `tform-i386`...
